googlefonts/colr-gradients-spec

colr-gradients-spec.md

This incorporates a few proposed changes that arose from discussions with @PeterConstable in
https://github.com/googlefonts/colr-gradients-spec/issues/14
https://github.com/googlefonts/colr-gradients-spec/issues/17
https://github.com/googlefonts/colr-gradients-spec/issues/18
https://github.com/googlefonts/colr-gradients-spec/issues/19
https://github.com/googlefonts/colr-gradients-spec/issues/21

16-bit GIDs, remove Point struct, rename transparency -> alpha, and other renames

---

colr-gradients-spec.md
images/clock-1.svg
images/clock-2.svg
images/clock-common.svg

Take two (take 1 was #35) at layer compositing and alpha. Changes layer structure to a DAG based on chat with @behdad and @drott. 
- Modes are as per https://www.w3.org/TR/compositing-1/
- Most implementations already support most modes
- D2D is notable in that it seems to have relatively few of the modes
- sources
- https://developer.apple.com/documentation/coregraphics/cgblendmode?language=objc
- https://www.cairographics.org/operators/
- https://docs.microsoft.com/en-us/windows/win32/api/d2d1_1/ne-d2d1_1-d2d1_composite_mode
- https://source.chromium.org/chromium/chromium/src/+/master:third_party/skia/include/core/SkBlendMode.h
Fixes #13.
The diff is a bit hard to read, https://github.com/googlefonts/colr-gradients-spec/blob/rs/colr-gradients-spec.md#compositing shows the updated md. …

Support layer compositing and alpha, mk2

---

colr-gradients-spec.md

Move the sections on DAG only, layer boundedness and bounding box to a
new section constraints to describe how they're normative restrictions.

Organize restrictions into Constraints section

---

colr-gradients-spec.md

Instead of italic, use headings for tables and records (per @drott comment, hopefully correctly interpreted here)

Use headings fo the tables/records

---

colr-gradients-spec.md

There is a note that glyph outline clips in the description of PaintGlyph. This PR fixes a few stray references to Filled.
I believe combined with the descriptive text this fixes #60

All the way back to PaintGlyph :)

---

colr-gradients-spec.md

The C++ templates were updated in https://github.com/googlefonts/colr-gradients-spec/pull/59 to use `Offset24` for PaintRadialGradient's offset to ColorLine. However the table definition still had the old `uint16` format and `Offset32`.
Make the table definition match the C++ template and use `uint8` format and `Offset24`.

make PaintRadialGradient use Offset24

---

colr-gradients-spec.md

Allow reuse of a slice of another COLR glyph
Fixes #86 
EDIT: generalized to a new paint format that points to a series of paint pointers, ty @behdad

Allow reuse of a subset of the layers of another COLR glyph

---

colr-gradients-spec.md

Main changes are in description of Affine2x3. As @drott commented in #85,
> as the matrix does not contain basis vectors, but coefficients
So `x-part of x-basis vector` is not really correct. (By convention, the x-part of the x-basis vector would always be 1! The matrix coefficients related to how the basis vector _gets transformed_.)
I separated `_v' = M * v =...` into two lines for better clarity. (The "," gets lost.)
`def paint` isn't prototypical pseudocode; it's Python, and could be unfamiliar to many readers.

misc tweaks

---

colr-gradients-spec.md

Clarify edge cases in note. Remove mention of degenerate radial gradient
transformation matrix as we removed the tranformation matrix from the
gradient definition when we added transforms.
Addresses parts of #22.

Clarify edge cases of radial gradients

---

colr-gradients-spec.md

add alternate transform representation in PaintTransformed

---

colr-gradients-spec.md

Moved transform content; no other changes except for headings.

Move Transformations content into OFF annex

---

colr-gradients-spec.md

Last reference was inadvertently dropped while resolving merge conflicts: I couldn't remember how the commit sequence went for these references (I had added one not related to the section being added in that commit, so for that PR removed it).

Restore missing ref (inadvertently dropped)

---

colr-gradients-spec.md

Short intro to 5.7.11.2 COLR table formats, and setting up headings for sub-clauses. Some PRs moving more existing content into these sub-clauses will follow after this PR is merged.
I'd like feedback on the sub-clause headings for the various paint formats: they can be named to reflect the functionality provided each format, or use the structure name. The latter alternative would be as follows:
>**5.7.11.2.5.1 Format 1: PaintColrLayers**
>
>**5.7.11.2.5.2 Format 2: PaintSolid**
>
>**5.7.11.2.5.3 Format 3: PaintLinearGradient**
>
>**5.7.11.2.5.4 Format 4: PaintRadialGradient**
>
>**5.7.11.2.5.5 Format 5: PaintGlyph**
>
>**5.7.11.2.5.6 Format 6: PaintColrGlyph**
>
>**5.7.11.2.5.7 Format 7: PaintTransformed**
>
>**5.7.11.2.5.8 Format 8: PaintRotate**
>
>**5.7.11.2.5.9 Format 9: PaintSkew** …

Set up headings for 5.7.11.2 COLR table formats

---

colr-gradients-spec.md

Moved without change to a new sub-clause at the end of 5.7.11.1 Graphic Compositions. A separate PR with revisions will follow.

Move Acyclic Graphs Only content to annex

---

colr-gradients-spec.md

Add PaintTranslate

---

colr-gradients-spec.md

The note in 5.7.11.2.5.6 is removed since the content was incorporated into 5.7.11.1.7.3 (this PR has a small change to that content).

Update PaintGlyph, PaintColrGlyph

---

colr-gradients-spec.md

Replaced the old "Alpha" section (move/edit) with an addition to 5.7.11.1.6 Compositing and blending. This gets rid of the last bit of the original "OFF changes" section.
With a figure inserted, following figures are renumbered. And since the same figure is used (to illustrate something different) in 5.7.11.1.9, that has a minor change to indicate the repeated figure.

Add alpha mask example to 'Compisiting and blending' section

---

colr-gradients-spec.md

Coming back to #168 — this is the issue that, if a sub-graph is ignored (e.g., the glyphID in PaintColrGlyph is bad), then the remainder of the graph could be unbounded.

Update 5.7.11.1.9 to cover well-formedness/validity

---

colr-gradients-spec.md

Small wording change in the rendering algorithm to clarify applying glyph outlines to the clip region (intersect current clip, i.e., do just replace the clip)

tweak rendering algo wording

---

colr-gradients-spec.md

In equations, variable letters should be italicized, but not other characters.

Fix formatting in equations

---

OFF_AMD2_WD.md

Addresses #200 
I also noticed the preceding paragraph had a wording issue: it refers to "stop offset", which is a remnant from an earlier revision in which a specific example involving the ColorIndex struct had been used. That was changed so that a generic Var* struct was described, but the wording in the following paragraph wasn't adjusted accordingly.

Rev details re Var* structures in COLR

---

OFF_AMD2_WD.md

This is to address the issue Vlad raised in #206 that the term "circumference" was being used incorrectly.
The wording "draw the circumference" was taken from the HTML Canvas spec. I'm guessing the intent in using that wording was to convey that what is drawn in the circular path but not the interior region, and that "draw the circle" might be misunderstood to include the interior region. In this initial commit, I've proposed the wording "draw the circular path" to retain that meaning.

Revise wording for radial gradient algorithm

---

OFF_AMD2_WD.md

See #150—this case was already covered in the statement of the algorithm.

For radial gradient, clarify if circles are identical

---

OFF_AMD2_WD.md

There's a little bit of intro-to-concepts content since readers of the OFF/OT spec come from a wide variety of backgrounds, and jumping straight to a statement like "compute using linear RGB" won't mean anything for many.
Linear RGB for blending isn't added here since that's will fit better in the COLR section on compositing, so will come separately. But a "for more info" pointer to the CPAL section can be included.

Add CPAL edits re sRGB 'gamma' and interpolation

---

OFF_AMD2_WD.md
colr-gradients-spec.md

`PaintRotate` and `PaintSkew` contain `centerX` and `centerY` for their respective center point, would be nice if also PaintSweepGradient used the same nomenclature for consistency.

PaintSweepGradient: rename x -> centerX, y -> centerY

---

OFF_AMD2_WD.md

For background on this change, see <https://github.com/MicrosoftDocs/typography-issues/issues/481>.

Revise change to 7.2.3.4

---

OFF_AMD2_WD.md
colr-gradients-spec.md

Sometimes we use "PaintTransform", other times "PaintTransformed".
I prefer to use "PaintTransform", without the final "ed". That's what I also used in the fontTools/ttx implementation.
Note that also the other transform-like paints are called PaintRotate, PaintSkew, PaintTranslate, not "PaintRotated", "PaintSkewed", etc.

Rename PaintTransformed -> PaintTransform

---

OFF_AMD2_WD.md

The convention used in OFF (and in OT) is to have simply "Name", not "Field name".

Change struct table headings 'Field name' to 'Name'

---

OFF_AMD2_WD.md
colr-gradients-spec.md

This is a start of the changes needed to add v1 formats without variation indices. This adds additional formats for gradients, but not yet for transforms.
I'll also need to look through the entire doc to see where else changes will be needed. And colr-gradients-spec.md will also need updating.

Start revisions to add no-var formats

---

OFF_AMD2_WD.md

Spec doesn't need to dictate choice of varstore, leave options open and let the compiler implementer decide. They'll have better data on the tradeoffs, may choose to emit multiple editions for different targets, etc.

Remove restriction on varstore; compiler should have freedom to decide.

---

OFF_AMD2_WD.md

Fixes #271. Rationale:
1. Allowing virtual gids isn't _useful_ for anything, notably it won't allow us to save gids
1. Complicates implementations; being able to use gid as globally unique is useful
1. ...I swear there was another reason but it's escaping me

Remove virtual gids

---

OFF_AMD2_WD.md
colr-gradients-spec.md

Based on exploration done for #283, #298 gains from sharing structures tends to outweigh trimming offsets

Make the 2x3 an offset

---

OFF_AMD2_WD.md
colr-gradients-spec.md

Exploit the follow observations from test fonts:
1. The most common translation is by an integer that fits within int16 so change dx/dy to Int16
1. The most common rotation is by < 360° so change angles to F2Dot14 where 1.0 means 180° counter-clockwise
1. The most common scales are small, it's rare to want a massively larger/smaller version of something, so use F2Dot14 scales
1. The most common center for a transformation is an integer that fits within int16 so change centerX/Y to Int16
Note that:
1. In all cases full precision can be achieved by using the full 2x3 whose types are unchanged.
1. Variation can be used to access greater range, such as if you want an axis that causes many rotations.

Reduce precision for all transforms added for compactness

---

OFF_AMD2_WD.md

Fix type F2DOT14 and some other details.
I don't think we need to explain in the spec why the F2DOT14 representation with 1.0 = 180º is used.

rev details for reduced precision in transforms

---

OFF_AMD2_WD.md
colr-gradients-spec.md

With the fifth commit, this is **NOW COMPLETE**.
This will supersede PR #306.
In the section on COLR and variations (5.7.11.4), some details regarding potential edge cases needed to be covered.
>If the COLR table does not contain an Item Variation Store subtable, the _varIndexBase_
field of variable tables or records shall be ignored by applications, and should be set to
zero.
This maintains what was previously there but re-cast into the new model.
>If the index for a variable item is greater than or equal to the number of entries in the mapping array, the last mapping array entry shall be used.
This follows what is already done in [HVAR](https://docs.microsoft.com/en-us/typography/opentype/spec/hvar).
>The sequence of indices derived from a _varIndexBase_ value do not wrap on overflow …

use DeltaSetIndexMap instead of VarFWord, etc. structs

---

OFF_AMD2_WD.md
colr-gradients-spec.md

Changes for #318 per F2F discussion.
Changes at lines 260 – 269 and 1550 – 1553 only correct to the desired line wrap in .md source—no substantive changes.

Drop ColorIndex, flatten color stop & paint solid structures

---

OFF_AMD2_WD.md
colr-gradients-spec.md

Strawman for a fix for #251. Costs 16 bytes per BaseGlyphPaintRecord ... but for a font that doesn't _have_ an alternate presentation you get some of them back by not writing out bogus glyph records just to express bboxes (as our exploratory compiler does today).
Edit: Fixes #251

Give COLR an explicit bbox to call it's own

---

OFF_AMD2_WD.md
colr-gradients-spec.md

Based on further discussion in https://github.com/googlefonts/colr-gradients-spec/pull/321, make the variable nature of bbox optional following the usual format model.
Fixes #323.

Allow variable and static bbox

---

OFF_AMD2_WD.md

Change for #319.
This is a little involved since it requires pulling description of the DeltaSetIndexMap out of the HVAR section into the OT Var Common Formats section (as well as re-defining the structure and adding format 1).

Rev DeltaSetIndexMap for formats 0 and 1

---

OFF_AMD2_WD.md
colr-gradients-spec.md

Fixes https://github.com/googlefonts/colr-gradients-spec/issues/346

define ClipList.format (0) to make it more futureproof

---

colr-gradients-spec.md

Revised some field names for greater consistency internally and with the OT/OFF spec names.
Also revised description of ClipList to use ArrayOf as elsewhere in the C++ header.

Rev C++ header for greater consistency

---

colr-gradients-spec.md

The pseudocode for compositing was missing one layer allocation. This
would result in incorrectly drawing BackdropPaint just on the previous
state of the canvas, then compositing the source paint down on
everything, instead of compositing backdrop and source first, then
applying the result to the current state of the canvas.

Fix pseudocode for compositing step
