colr-gradients-spec.md
Add reuse by group to COLRv1. Once acceptable will circle back to add blend mode.
Fixes #32.
=> First draft of PaintGroup (per Behdad proposal on #32)

colr-gradients-spec.md
=> Attempt to clarify bounding box.

colr-gradients-spec.md
=> Clarify alpha is multiplied

colr-gradients-spec.md
=> Specify what to do if you don't recognize a composite mode

colr-gradients-spec.md
=> Friendlier name for PaintGlyph, reordering of formats

colr-gradients-spec.md
Also remove the special rules for handling that 2x2.
=> Remove radial gradient 2x2, clarify PaintTransformed interaction with gradients

colr-gradients-spec.md
=> Use Offset24 where doing so would put it alongside a single byte

colr-gradients-spec.md
C++ code kept, moved into the Implementation section.
=> Incorporate OT/OFF style struct definitions

colr-gradients-spec.md
Group primitives, add transforms, composites. Explain high level design to be mapped to 2d graphics library primitives.
=> Extend and clarify graphical primitives / paints

colr-gradients-spec.md
Changes in support of #73; closes #73.
Review updated proposal @ https://github.com/googlefonts/colr-gradients-spec/tree/off_sub_1 if the diff is painful.
=> Prepare for OFF submission

colr-gradients-spec.md
=> Fix reference to OVER

colr-gradients-spec.md
Shift remaining format numbers up. Sort pseudocode loop by formats.
Fixes #90.
=> Insert PaintColrLayers as format number 1

colr-gradients-spec.md
=> Define sort order for entries of BaseGlyphV1List

colr-gradients-spec.md
=> Fix Note styling, caption and note order

colr-gradients-spec.md
As suggested on #108, fixes #108
=> Use "shall" instead of "must" in several places

colr-gradients-spec.md
First PR in restructure sequence
=> Begin restructuring content to better organize OFF proposal

colr-gradients-spec.md
OFF bibliography moved without changes
=> Move OFF Bibliography section to annex

colr-gradients-spec.md
Move section with only one small edit (add missing ":" on last line)
=> Move OFF 7.2.3 IVS to annex

colr-gradients-spec.md
Moved composition content; no other changes except headings.
=> Move composition content into OFF annex

colr-gradients-spec.md
Move radial gradient content, no other changes except for headings.
=> Move radial gradient content into OFF annex

colr-gradients-spec.md
New content; nothing moved. If there were anything this corresponds to to be moved, it's content in the current OFF that's not in this doc. If you think there is content it corresponds to that should be moved, please let me know what.
=> add content for 5.7.11.1.1 colors & solid color fills

colr-gradients-spec.md
Moved color line section without changes. Only other changes were addition of sub-clause headings and opening intro paragraph for 5.7.11.1.2.
=> Move color line content into OFF annex

colr-gradients-spec.md
Moved linear gradient content without changes other than headings.
=> Move linear gradient content into OFF annex

colr-gradients-spec.md
=> fix wording

colr-gradients-spec.md
=> minor wording change

colr-gradients-spec.md
Move without changes (except for heading).
=> Move Reusable parts section

colr-gradients-spec.md
Move existing contents into annex with only limited changes:
* dropped existing headings (using OFF sub-clause headings already added)
* dropped original intro text (no longer needed)
* dropped variation structures (these were already incorporated into text for clause 7.2.3.1 and could have been removed earlier)
* moved Affine2x3 record into same sub-clause as PaintTransformed
=> Move formats into annex

colr-gradients-spec.md
Update:
* 5.7.11.2.5.3 Format 3: PaintLinearGradient
* 5.7.11.2.5.4 Format 4: PaintRadialGradient
=> Update PaintLinearGradient, PaintRadialGradient

colr-gradients-spec.md
* Add intro: 5.7.11.2.5 Paint tables
* Update 
* 5.7.11.2.5.1 Format 1: PaintColrLayers
* 5.7.11.2.5.2 Format 2: PaintSolid
=> Add Paint tables intro; update formats 1, 2

colr-gradients-spec.md
Fix pending OFF-internal references (getting rid of temporary inline HTML) and reformat lines (break at 80 columns). No other changes.
=> Fix ref ##; reformat lines

colr-gradients-spec.md
Draft of rendering algorithm -- let's discuss
=> Add draft for rendering algorithm

colr-gradients-spec.md
Change per missed comment on PR #185
=> Rev rendering algo text per final PR comment.

colr-gradients-spec.md
Last sub-clause to be added to 5.7.11 COLR
=> Add section on variations

OFF_AMD2_WD.md
=> Rev typography for refs to 'Source In' and 'Source Out'

OFF_AMD2_WD.md, colr-gradients-spec.md
=> Add composite plus

OFF_AMD2_WD.md
This is proposed text to address #196
=> For lin grad, clarify effect of rot'n vector if angle is >90

OFF_AMD2_WD.md
Pulled this commit out of PR #217. (Rod had commented on this wording in that PR, but Dominik suggested the change be in a separate PR.)
=> Revise wording re filling shapes

OFF_AMD2_WD.md
As discussed in F2F: it's not self-evident how a rotation or skew expressed as an angle should combine with a matrix.
=> Clarify how PaintRotate or PaintSkew combine with other transforms

OFF_AMD2_WD.md
Similar wording for linear gradients has been included in PR #219
=> describe transforms applied to radial or sweep gradients

OFF_AMD2_WD.md, colr-gradients-spec.md
=> Revise wording to clarify bounding box

OFF_AMD2_WD.md
=> Clarify result if radial gradient circles are flattened

OFF_AMD2_WD.md
=> Add wording to clarify color line intervals

OFF_AMD2_WD.md
As I had to re-read all of 5.7.11, I made a few additional, very minor wording edits along the way.
=> Additional changes in 5.7.11 COLR to incorporate non-variable formats

OFF_AMD2_WD.md
=> Add discussion of bounding box and variations

OFF_AMD2_WD.md
Incorporates Vlad's suggestions (offline) and also includes a fix of the bad typo in figures 5.18 - 5.20 ("string" s/be "strip").
=> Misc edits to sync with AHG drafts

OFF_AMD2_WD.md
Revise the description per Vlad's comments
=> Improve description of CompositeMode enum

OFF_AMD2_WD.md
=> rev wording describing color lines

OFF_AMD2_WD.md
Minor wording changes noted while preparing addition of PaintScale and variants.
=> fix typo and minor wording change

OFF_AMD2_WD.md, colr-gradients-spec.md
=> Revise struct names to remove 'V1'

OFF_AMD2_WD.md, colr-gradients-spec.md
Make all the angle fields consistent.
Smallest rotation in degrees (ty @anthrotype for pointing this out)
```
>>> 1/(1<<14)*180
0.010986328125
```
=> All angles in F2Dot14

OFF_AMD2_WD.md, colr-gradients-spec.md
See #308 and #307 for discussion about whether this is or isn't a good idea.
=> Center => FWORD

OFF_AMD2_WD.md
Added note to accommodate request from @Lorp in #308.
=> Add note re chained transforms

OFF_AMD2_WD.md, colr-gradients-spec.md
=> Provide an optional clip box instead of a mandatory bbox

OFF_AMD2_WD.md
=> add clarification re PaintRotate angles and variations

OFF_AMD2_WD.md
Recommendation added in relation to #339, plus one editorial addition.
=> Add recommendation regarding use of LONG_WORDS flag
